/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Lenses: THREE.Mesh;
    Frame: THREE.Mesh;
    Branches: THREE.Mesh;
    Head: THREE.Mesh;
    Text: THREE.Mesh;
    Text2: THREE.Mesh;
    text: THREE.Mesh;
    frame2: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(
    "/bailefun_webgl.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lenses.geometry}
        material={materials.Material}
        position={[0.115, 0.868, 1.739]}
        rotation={[1.296, 0.003, -0.011]}
        scale={[0.191, 0.191, 0.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Frame.geometry}
        material={materials['Material.006']}
        position={[0.118, 0.941, 1.821]}
        rotation={[-0.27, 0.006, 0.002]}
        scale={[0.081, 0.067, 0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Branches.geometry}
        material={materials['Material.006']}
        position={[0.137, 0.779, 2.066]}
        rotation={[-0.222, 0.011, 0.003]}
        scale={[0.228, 0.189, 0.228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Head.geometry}
        material={materials['Material.003']}
        position={[0.118, 0, -0.02]}
        rotation={[0, -1.542, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Textn.geometry}
        material={materials['Material.001']}
        position={[-0.033, 0.298, -0.715]}
        rotation={[0.582, -1.536, -0.274]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Textu.geometry}
        material={materials['Material.001']}
        position={[-0.033, 0.298, -0.715]}
        rotation={[0.582, -1.536, -0.274]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Textf.geometry}
        material={materials['Material.001']}
        position={[-0.033, 0.458, -0.715]}
        rotation={[0.582, -1.536, -0.274]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Textbaile.geometry}
        material={materials['Material.001']}
        position={[0.059, 0.123, -0.454]}
        rotation={[1.305, 0, -0.029]}
      />
      <group
        position={[1.283, 0.557, 0.311]}
        rotation={[-0.049, 0.037, 0.124]}
        scale={[0.73, 0.6, 0.73]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.frame2.geometry}
          material={materials['Material.006']}
          position={[-1.676, 0.472, 1.967]}
          rotation={[-0.176, 0.009, -0.167]}
          scale={0.03}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/bailefun_webgl_2.glb");
