/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cubo: THREE.Mesh;
    Cubo001: THREE.Mesh;
    Cubo003: THREE.Mesh;
    Círculo001: THREE.Mesh;
    Icosphere001: THREE.Mesh;
  };
  materials: {
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["texrtura lentes"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/bailefun_webgl.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[1.283, 0.557, 0.311]}
        rotation={[-0.005, 0.037, 0.124]}
        scale={[0.73, 0.6, 0.73]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cubo.geometry}
          material={materials["Material.002"]}
          position={[0.906, 0.206, -0.373]}
          rotation={[-1.298, 1.418, 1.305]}
          scale={0.313}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cubo001.geometry}
          material={materials["Material.002"]}
          position={[0.861, 0.517, -0.381]}
          rotation={[-1.315, 1.419, 1.322]}
          scale={0.111}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cubo003.geometry}
          material={materials["Material.002"]}
          position={[1.04, 0.24, -0.379]}
          rotation={[-1.315, 1.419, 1.333]}
          scale={0.03}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Círculo001.geometry}
          material={materials["texrtura lentes"]}
          position={[0.882, 0.441, -0.383]}
          rotation={[1.575, 0.147, -1.533]}
          scale={0.262}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere001.geometry}
        material={materials["Material.003"]}
        position={[0, 0, -0.001]}
        scale={2}
      />
    </group>
  );
}

useGLTF.preload("/bailefun_webgl.glb");
