/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Lenses001: THREE.Mesh;
    Frame001: THREE.Mesh;
    Branches: THREE.Mesh;
    head001: THREE.Mesh;
    text003: THREE.Mesh;
    text002: THREE.Mesh;
    text001: THREE.Mesh;
    text: THREE.Mesh;
    frame2: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
  };
};

type ActionName =
  | "text.001Action.002"
  | "text.001Action.001"
  | "text.001Action"
  | "textAction";
// type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    "/bailefun_webgl.glb"
  ) as GLTFResult;
  //   const { actions } = useAnimations<GLTFActions>(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="Lenses001"
        castShadow
        receiveShadow
        geometry={nodes.Lenses001.geometry}
        material={materials.Material}
        position={[1.758, 0.868, 0.008]}
        rotation={[1.566, 0.275, -1.553]}
        scale={[0.191, 0.191, 0.158]}
      />
      <mesh
        name="Frame001"
        castShadow
        receiveShadow
        geometry={nodes.Frame001.geometry}
        material={materials["Material.002"]}
        position={[1.84, 0.941, 0.008]}
        rotation={[-1.49, 1.299, 1.487]}
        scale={[0.081, 0.067, 0.081]}
      />
      <mesh
        name="Branches"
        castShadow
        receiveShadow
        geometry={nodes.Branches.geometry}
        material={materials["Material.002"]}
        position={[2.085, 0.779, -0.005]}
        rotation={[-1.494, 1.348, 1.492]}
        scale={[0.228, 0.189, 0.228]}
      />
      <mesh
        name="head001"
        castShadow
        receiveShadow
        geometry={nodes.head001.geometry}
        material={materials["Material.003"]}
        position={[0, 0, -0.001]}
        scale={2}
      />
      <mesh
        name="text003"
        castShadow
        receiveShadow
        geometry={nodes.text003.geometry}
        material={materials["Material.005"]}
        position={[-1.717, -0.291, 0.056]}
        rotation={[0.019, 0, -0.855]}
      />
      <mesh
        name="text002"
        castShadow
        receiveShadow
        geometry={nodes.text002.geometry}
        material={materials["Material.004"]}
        position={[-1.717, -0.291, 0.056]}
        rotation={[0.019, 0, -0.855]}
      />
      <mesh
        name="text001"
        castShadow
        receiveShadow
        geometry={nodes.text001.geometry}
        material={materials["Material.001"]}
        position={[-1.717, -0.506, 0.056]}
        rotation={[0.019, 0, -0.855]}
      />
      <mesh
        name="text"
        castShadow
        receiveShadow
        geometry={nodes.text.geometry}
        material={materials["Material.006"]}
        position={[-1.717, -0.291, 0.056]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <group name="BézierCircle" />
      </mesh>
      <group
        name="Empty002"
        position={[1.283, 0.557, 0.311]}
        rotation={[-0.049, 0.037, 0.124]}
        scale={[0.73, 0.6, 0.73]}
      >
        <mesh
          name="frame2"
          castShadow
          receiveShadow
          geometry={nodes.frame2.geometry}
          material={materials["Material.007"]}
          position={[0.756, 0.248, -0.342]}
          rotation={[-0.988, 1.467, 1.02]}
          scale={0.03}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/bailefun_webgl.glb");
